version: '3.2'
services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "whizlabs"
      MYSQL_DATABASE: "whizlabs"
    ports:
      - "3306:3306"
    volumes:
      - whizlabsdb:/var/lib/mysql
    networks:
      - mysql-compose-network

  adminer:
    image: adminer
    ports:
      - 18080:8080
    networks:
      - mysql-compose-network

volumes:
  whizlabsdb:

networks: 
  mysql-compose-network:
    driver: bridge